TARGET_BOOTLOADER_BOARD_NAME := mt6572
TARGET_BOARD_PLATFORM := mt6572

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6572
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# not sure if this is working...
TARGET_USERIMAGES_USE_EXT4 := true

# partition sizes, from /proc/dumchar_info
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x600000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x600000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 681574400
BOARD_USERDATAIMAGE_PARTITION_SIZE := 86769664
BOARD_FLASH_BLOCK_SIZE := 131072

# openGL
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := device/alps/mt6572/egl.cfg

# some properties
TARGET_PREBUILT_KERNEL := device/alps/mt6572/kernel
BOARD_HAS_NO_SELECT_BUTTON := true

